/**
 * NodeTrace v2 — the MERGED loop trajectory.
 *
 * The three components of the NodeRoom proof-loop each emit a slice of the same run:
 *  - the OUTER trace (a browser-driven UI proof: room URL, before/during/after screenshots, UI assertions),
 *  - the INNER trace (the agent's own plan -> tool -> write -> verify reasoning steps, with cost/latency),
 *  - the ARTIFACTS the run produced (sheets/notes/decks, with export + reopen proof),
 *  - the EVIDENCE facts the run grounded (source_backed / needs_review / ...).
 * `NodeMergedTrajectory` is the canonical join of all four into ONE object that SFT / DPO / RLVR
 * pipelines and the Trace Storybook both read. This file is HAND-MAINTAINED net-new code (like
 * trajectory.ts): it is NOT in MANIFEST.json and NOT re-exported from the generated index.ts (both are
 * regenerated by the extractor and would clobber edits). It is reachable via the "./merged" subpath
 * export. It imports ONLY the deterministic-id helper from "./trajectory" — no runtime capture types.
 *
 * Design invariants (root-caused, each enforced below — same doctrine as trajectory.ts):
 *  - DETERMINISTIC: no Date.now / Math.random / new Date. `trajectoryId`, when not supplied, is a
 *    sorted-key FNV-1a hash (reused verbatim from trajectory.ts::deterministicId) of stable inputs.
 *    Same logical input twice => byte-identical object.
 *  - HONEST_SCORES: mergeTrajectory NEVER fabricates a reward. It attaches a reward ONLY if the caller
 *    supplies one; when it does normalize a partial reward, any component NOT supplied is set to 0 AND
 *    labeled "unscored:<name>" — never a hardcoded floor. There is no per-task answer key here.
 *  - HONEST_STATUS: a failed `uiAssertion` (passed:false) or a `needs_review` evidence fact is carried
 *    verbatim; the merge never flips it to passed/source_backed. The failure is the RL signal.
 *  - NO-LEAK / BOUNDED: screenshots are PATHS only. mergeTrajectory refuses (throws) if a screenshot
 *    path is actually inlined bytes (a data: URI, or a Uint8Array/Buffer that slipped into the field).
 *  - SEQUENTIAL: `innerTrace.steps[i].stepIndex` is re-stamped 0..n so the merged trace always has a
 *    contiguous, gap-free index regardless of what the inner slice supplied.
 */
import { deterministicId } from "./trajectory";

/* ------------------------------------------------------------------------------------------------ *
 * The canonical loop object. All three components (outer / inner / product) share this EXACT shape.  *
 * ------------------------------------------------------------------------------------------------ */

/** A UI-level check the outer proof made against the live room. `passed:false` is an honest failure. */
export interface UiAssertion {
  id: string;
  expected: string;
  observed: string;
  passed: boolean;
}

/**
 * An outer-loop screenshot. `path` is a stored ref (file path / object-store key), NEVER inlined bytes
 * (NO-LEAK). `visibleComponentIds` optionally records which surface components were on screen for the box/
 * attention-overlay layer.
 */
export interface OuterScreenshot {
  label: "before" | "during" | "after" | "failure" | "focus";
  path: string;
  visibleComponentIds?: string[];
}

/**
 * One reasoning step of the INNER (agent) trace. `stepIndex` is re-stamped sequential by mergeTrajectory.
 * `artifactRefs`/`evidenceRefs` cross-link into the merged `artifacts`/`evidence` arrays. Cost/latency are
 * carried verbatim when known — never invented.
 */
export interface MergedStep {
  stepIndex: number;
  phase: "plan" | "tool" | "write" | "verify" | "repair" | "final";
  action: string;
  observation: string;
  toolName?: string;
  artifactRefs?: string[];
  evidenceRefs?: string[];
  costUsd?: number;
  latencyMs?: number;
  error?: string;
}

/** A deliverable the run produced. `reopenPassed` is the honest "does it open again?" proof. */
export interface MergedArtifact {
  artifactId: string;
  kind: "sheet" | "note" | "deck" | "doc" | "pdf" | "graph";
  beforeHash?: string;
  afterHash?: string;
  exportPath?: string;
  reopenPassed?: boolean;
}

/** A grounded fact. `status` is carried verbatim — `needs_review` is never silently promoted. */
export interface MergedEvidence {
  factId: string;
  claim: string;
  sourceUrl?: string;
  quote?: string;
  status: "source_backed" | "manual" | "graph_inferred" | "needs_review";
}

/**
 * The reward summary. Every component is in [0,1] by product convention, but this type does not coerce —
 * mergeTrajectory carries supplied numbers verbatim and only zero-fills+labels the UNSUPPLIED ones. A
 * component that is not derivable from the trace is 0 AND recorded in `labels` as "unscored:<name>".
 */
export interface MergedReward {
  taskCompletion: number;
  uiStateCorrectness: number;
  visualQuality: number;
  evidenceGrounding: number;
  costEfficiency: number;
  latencyEfficiency: number;
  safety: number;
  total: number;
  labels: string[];
  failureCategories: string[];
}

/** The unit NodeTrace v2 records: the outer + inner + artifacts + evidence of one run, joined. */
export interface NodeMergedTrajectory {
  trajectoryId: string;
  runId: string;
  userGoal: string;
  outerTrace: {
    url: string;
    screenshots: OuterScreenshot[];
    consoleErrors: string[];
    uiAssertions: UiAssertion[];
  };
  innerTrace: {
    model?: string;
    steps: MergedStep[];
  };
  artifacts: MergedArtifact[];
  evidence: MergedEvidence[];
  reward?: MergedReward;
}

/* ------------------------------------------------------------------------------------------------ *
 * mergeTrajectory — the pure joiner.                                                                *
 * ------------------------------------------------------------------------------------------------ */

/** The seven scored reward components (everything on MergedReward except total/labels/failureCategories). */
export const MERGED_REWARD_COMPONENTS = [
  "taskCompletion",
  "uiStateCorrectness",
  "visualQuality",
  "evidenceGrounding",
  "costEfficiency",
  "latencyEfficiency",
  "safety",
] as const;
type MergedRewardKey = (typeof MERGED_REWARD_COMPONENTS)[number];

/** A reward aggregation formula. Receives the resolved components and returns the headline total. */
export type MergedRewardFormula = (components: Record<MergedRewardKey, number>) => number;

/**
 * Documented DEFAULT formula: a simple mean of the seven components. Intentionally generic (no per-task
 * answer key — that would be cheating). Product evals pass their own weighted formula when they have one.
 */
export const defaultMergedRewardFormula: MergedRewardFormula = (c) => {
  const sum = MERGED_REWARD_COMPONENTS.reduce((acc, k) => acc + c[k], 0);
  return sum / MERGED_REWARD_COMPONENTS.length;
};

/** The outer-loop slice a caller supplies. `screenshots` paths must be refs, not inlined bytes. */
export interface OuterTraceInput {
  url: string;
  screenshots: OuterScreenshot[];
  consoleErrors?: string[];
  uiAssertions?: UiAssertion[];
}

/** The inner-loop slice a caller supplies. `steps[*].stepIndex` is IGNORED — merge re-stamps it. */
export interface InnerTraceInput {
  model?: string;
  steps: MergedStep[];
}

/** Merge-level metadata: identity + optional reward. */
export interface MergeMeta {
  runId: string;
  userGoal: string;
  /** Explicit id; otherwise derived deterministically from stable inputs. */
  trajectoryId?: string;
  /** Product-side reward components (carried verbatim, never fabricated). Attached as `reward`. */
  reward?: Partial<MergedReward>;
  /** Optional reward formula; defaults to the documented mean when reward components are supplied. */
  rewardFormula?: MergedRewardFormula;
}

/** NO-LEAK guard: reject anything that is bytes rather than a stored screenshot ref/path. */
function assertNotInlinedBytes(path: unknown, where: string): asserts path is string {
  if (path instanceof Uint8Array || path instanceof ArrayBuffer) {
    throw new Error(`NO-LEAK violation: ${where} carries inlined bytes; screenshots must be paths only`);
  }
  if (typeof path !== "string") {
    throw new Error(`${where} must be a string path, got ${typeof path}`);
  }
  if (path.startsWith("data:")) {
    throw new Error(`NO-LEAK violation: ${where} is a data: URI (inlined bytes); screenshots must be paths only`);
  }
}

/** Stable de-dup preserving first-seen order (DETERMINISTIC: no cross-engine Set-iteration surprises). */
function dedupe(xs: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const x of xs) {
    if (!seen.has(x)) {
      seen.add(x);
      out.push(x);
    }
  }
  return out;
}

/**
 * Build the merged reward honestly.
 *  - Each supplied finite component is carried VERBATIM.
 *  - Each UNSUPPLIED component is 0 AND labeled "unscored:<name>" (HONEST_SCORES — never a floor).
 *  - `failureCategories` are derived from HONEST signals only: failed uiAssertions, needs_review evidence,
 *    steps carrying an `error`, and reopen-failed artifacts. Supplied categories are preserved first.
 *  - `total` = formula(resolvedComponents); supplied formula or the documented default mean.
 */
function buildReward(
  outer: NodeMergedTrajectory["outerTrace"],
  inner: NodeMergedTrajectory["innerTrace"],
  artifacts: MergedArtifact[],
  evidence: MergedEvidence[],
  supplied: Partial<MergedReward> | undefined,
  formula: MergedRewardFormula | undefined,
): MergedReward {
  const src = supplied ?? {};
  const labels: string[] = Array.isArray(src.labels) ? [...src.labels] : [];

  const resolved = {} as Record<MergedRewardKey, number>;
  for (const key of MERGED_REWARD_COMPONENTS) {
    const v = src[key];
    if (typeof v === "number" && Number.isFinite(v)) {
      resolved[key] = v;
    } else {
      resolved[key] = 0;
      labels.push(`unscored:${key}`);
    }
  }

  const failureCategories: string[] = Array.isArray(src.failureCategories)
    ? [...src.failureCategories]
    : [];
  if (outer.uiAssertions.some((a) => a.passed === false)) failureCategories.push("ui_assertion_failed");
  if (evidence.some((e) => e.status === "needs_review")) failureCategories.push("evidence_needs_review");
  if (inner.steps.some((s) => typeof s.error === "string" && s.error.length > 0)) failureCategories.push("step_error");
  if (artifacts.some((a) => a.reopenPassed === false)) failureCategories.push("artifact_reopen_failed");
  if (outer.consoleErrors.length > 0) failureCategories.push("console_error");

  const total = (formula ?? defaultMergedRewardFormula)(resolved);

  return {
    taskCompletion: resolved.taskCompletion,
    uiStateCorrectness: resolved.uiStateCorrectness,
    visualQuality: resolved.visualQuality,
    evidenceGrounding: resolved.evidenceGrounding,
    costEfficiency: resolved.costEfficiency,
    latencyEfficiency: resolved.latencyEfficiency,
    safety: resolved.safety,
    total,
    labels: dedupe(labels),
    failureCategories: dedupe(failureCategories),
  };
}

/**
 * Join the outer/inner/artifacts/evidence slices of one run into a canonical `NodeMergedTrajectory`.
 *
 * Pure and deterministic:
 *  - `innerTrace.steps` are copied with `stepIndex` re-stamped 0..n (SEQUENTIAL).
 *  - screenshots are validated to be paths, never inlined bytes (NO-LEAK) — a violation throws.
 *  - `trajectoryId` is `meta.trajectoryId` when supplied, else a sorted-key FNV-1a hash of stable inputs
 *    (DETERMINISTIC — same logical inputs => identical id).
 *  - a `reward` is attached ONLY when `meta.reward` is supplied; unsupplied components are 0 + labeled
 *    "unscored:<name>" (HONEST_SCORES). When no reward is supplied at all, `reward` is left undefined.
 */
export function mergeTrajectory(
  inner: InnerTraceInput,
  outer: OuterTraceInput,
  artifacts: MergedArtifact[],
  evidence: MergedEvidence[],
  meta: MergeMeta,
): NodeMergedTrajectory {
  // NO-LEAK: every screenshot must be a stored path, never bytes.
  outer.screenshots.forEach((s, i) => assertNotInlinedBytes(s.path, `outerTrace.screenshots[${i}].path`));

  // SEQUENTIAL: re-stamp stepIndex 0..n; copy each step so the caller's array is not mutated.
  const steps: MergedStep[] = inner.steps.map((s, i) => ({ ...s, stepIndex: i }));

  const outerTrace: NodeMergedTrajectory["outerTrace"] = {
    url: outer.url,
    screenshots: outer.screenshots,
    consoleErrors: outer.consoleErrors ?? [],
    uiAssertions: outer.uiAssertions ?? [],
  };

  const innerTrace: NodeMergedTrajectory["innerTrace"] = {
    ...(inner.model !== undefined ? { model: inner.model } : {}),
    steps,
  };

  const trajectoryId =
    meta.trajectoryId ??
    deterministicId("mtraj", {
      runId: meta.runId,
      userGoal: meta.userGoal,
      url: outerTrace.url,
      model: innerTrace.model ?? null,
      stepCount: steps.length,
      artifactIds: artifacts.map((a) => a.artifactId),
      evidenceIds: evidence.map((e) => e.factId),
      assertionIds: outerTrace.uiAssertions.map((a) => a.id),
    });

  const merged: NodeMergedTrajectory = {
    trajectoryId,
    runId: meta.runId,
    userGoal: meta.userGoal,
    outerTrace,
    innerTrace,
    artifacts,
    evidence,
  };

  // HONEST_SCORES: attach a reward ONLY when the caller supplied one; never fabricate a score.
  if (meta.reward !== undefined) {
    merged.reward = buildReward(outerTrace, innerTrace, artifacts, evidence, meta.reward, meta.rewardFormula);
  }

  return merged;
}
